## 为啥使用 Numpy

In [1]:
li1 = [1,2,3,4,5]
li2 = [6,7,8,9,10]

In [2]:
li = [6,14,24,36,50]

In [3]:
li = li1 * li2

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
li = [1,2,3,4,5,6]
li**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [5]:
import numpy as np

In [6]:
li1 = np.array([1,2,3,4,5])
li2 = np.array([4,5,6,7,8])

In [7]:
li1

array([1, 2, 3, 4, 5])

In [8]:
li2

array([4, 5, 6, 7, 8])

In [9]:
li1 * li2

array([ 4, 10, 18, 28, 40])

# li1 ** 2

In [11]:
li1 + li2

array([ 5,  7,  9, 11, 13])

In [12]:
li1 - li2

array([-3, -3, -3, -3, -3])

##  创建 ndarray

np.array()

### numpy的属性

In [14]:
li = np.array([1,2,3,4,5])

In [15]:
li

array([1, 2, 3, 4, 5])

In [16]:
li.dtype  ### 元素的类型

dtype('int32')

In [18]:
li.size ### 元素的个数

5

In [20]:
li.ndim ### 数组的维度

1

In [24]:
li.shape ### 数组维度的大小

(5,)

In [26]:
li2 = np.array([ [1,2,3,4,5], [6,7,8,9,10] ])

In [27]:
li2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
li2.ndim

2

In [30]:
li2.shape

(2, 5)

In [31]:
li = np.array([1,2,3,4,5], dtype='float')

In [32]:
li

array([1., 2., 3., 4., 5.])

In [33]:
li.astype('int')

array([1, 2, 3, 4, 5])

### 创建ndarray的几种方式

In [35]:
np.arange(0,10)  ### 生成一个nd数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [37]:
np.linspace?  ### 指定范围内生成指定的样本数量

In [39]:
np.linspace(2,3, num=50, endpoint=False)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98])

In [40]:
np.zeros?   #### 生成数量为n的0数组

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [44]:
np.ones(10)   ### 生成数量为n的1数组

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [46]:
li = np.ones(10)

In [47]:
li

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
li.reshape(2,5)   ### 改变数组的维度

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
li.reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
li.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

### 向量运算

In [51]:
li = np.array([1,2,24,6])


In [52]:
li + 1

array([ 2,  3, 25,  7])

In [53]:
li * 2

array([ 2,  4, 48, 12])

### 数组的索引

In [54]:
li = np.array([2,3,4,5,6,7,8,9])

In [55]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
li[2]

4

In [57]:
li1 = li.reshape(2,4)

In [58]:
li1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [61]:
li1[0,2]

4

In [62]:
li1[0][2]

4

### 数组切片 

In [63]:
li1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [64]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
li[0:3]

array([2, 3, 4])

In [66]:
li1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [67]:
li1[0:2, 1:3]

array([[3, 4],
       [7, 8]])

In [68]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
li[:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
li[:2]

array([2, 3])

In [71]:
li[3:]

array([5, 6, 7, 8, 9])

In [72]:
li1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [73]:
li1[:,1:]

array([[3, 4, 5],
       [7, 8, 9]])

In [74]:
li[-1:]

array([9])

### 布尔型索引

In [75]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
li > 4

array([False, False, False,  True,  True,  True,  True,  True])

In [77]:
li[li>4]

array([5, 6, 7, 8, 9])

In [78]:
(li > 5) & (li%2 == 0)

array([False, False, False, False,  True, False,  True, False])

In [79]:
li[(li > 5) & (li%2 == 0)]

array([6, 8])

## 花式索引 

In [80]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
li[ [1,3,6] ]

array([3, 5, 8])

## 通用函数

In [82]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
li.sum()

44

In [84]:
np.sum(li)

44

In [85]:
li.mean() 

5.5

In [87]:
np.abs(li)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.sqrt(li)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        ])

In [90]:
np.ceil(li)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
li1 = np.linspace(2,8, 10)

In [93]:
li1

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [94]:
np.ceil(li1)

array([2., 3., 4., 4., 5., 6., 6., 7., 8., 8.])

In [95]:
np.floor(li1)

array([2., 2., 3., 4., 4., 5., 6., 6., 7., 8.])

In [98]:
np.rint?

In [97]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.trunc?

In [101]:
np.isnan(li)  ## Nan === None

array([False, False, False, False, False, False, False, False])

In [102]:
np.isinf(li)

array([False, False, False, False, False, False, False, False])

In [103]:
np.maximum?

In [106]:
np.nan

nan

In [107]:
li.sum()

44

In [109]:
li.mean()

5.5

In [110]:
li.var()

5.25

In [111]:
li

array([2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
### 方差
#((2-5.5) ** 2 + (3-5.5) ** 2 + )/8

## numpy的随机函数

In [113]:
import random

In [120]:
random.randint(1,10)

7

In [124]:
np.random.rand(10)  ## 0 -1 之间,生成10个数

array([0.47789816, 0.08391206, 0.78847252, 0.32092018, 0.31135173,
       0.30108716, 0.46324715, 0.30554912, 0.47291117, 0.65493354])

In [126]:
np.random.randint(1,10, 10)

array([1, 1, 5, 9, 9, 1, 5, 6, 3, 6])

In [127]:
np.random.choice?

In [128]:
np.random.shuffle?

In [130]:
a = np.arange(10)

In [132]:
li = np.random.shuffle(a)

In [133]:
a

array([5, 9, 3, 7, 1, 8, 6, 2, 0, 4])

In [134]:
np.random.uniform?

In [135]:
s = np.random.uniform(-1,0,1000)
s

array([-5.68799603e-01, -9.80353146e-02, -7.92896173e-01, -4.08402882e-01,
       -1.30930227e-01, -5.73777772e-01, -1.04164664e-01, -1.42797227e-01,
       -8.03556000e-01, -8.90543043e-01, -6.24499968e-01, -1.21432391e-01,
       -8.87867552e-01, -6.43119919e-02, -1.60061733e-01, -5.19232758e-01,
       -4.88260322e-01, -2.96147796e-01, -3.93206693e-01, -1.55798538e-02,
       -3.71522095e-01, -4.55735077e-01, -2.20783837e-01, -6.95349534e-01,
       -7.90678783e-01, -9.39292931e-01, -2.87256974e-01, -7.57542756e-01,
       -7.85551958e-01, -3.97675922e-01, -6.41138419e-01, -7.48223416e-01,
       -4.35233048e-01, -3.72570270e-01, -9.75964910e-01, -1.88945242e-02,
       -2.87413737e-01, -7.98574373e-01, -8.85058825e-02, -6.19877309e-01,
       -7.47825047e-01, -5.28101186e-01, -1.01044020e-01, -6.10764019e-01,
       -3.70945165e-01, -8.78337067e-01, -2.20079794e-01, -3.04279361e-01,
       -7.08817537e-01, -6.08176394e-01, -7.94412299e-01, -7.28042573e-02,
       -3.63618866e-01, -